### ISSUE TITLE
Uncaught RequestException

### ISSUE THREAD

**Issue by BigJabber** [MyParcelCOM/api-sdk-php#106] opened 2019-08-19 16:07 UTC
Hi,

I've just attempted to authenticate with the sandbox and I'm getting an uncaught exception when an error code greater than 400 is received.

`Uncaught MyParcelCom\ApiSdk\Http\Exceptions\RequestException: Not Found in /var/www/html/integration/vendor/myparcelcom/api-sdk/src/Authentication/ClientCredentials.php:135
Stack trace:
#0 /var/www/html/integration/vendor/myparcelcom/api-sdk/src/Authentication/ClientCredentials.php(81): MyParcelCom\ApiSdk\Authentication\ClientCredentials-&gt;authenticate()
#1 /var/www/html/integration/vendor/myparcelcom/api-sdk/src/MyParcelComApi.php(623): MyParcelCom\ApiSdk\Authentication\ClientCredentials-&gt;getAuthorizationHeader()
#2 /var/www/html/integration/vendor/myparcelcom/api-sdk/src/MyParcelComApi.php(609): MyParcelCom\ApiSdk\MyParcelComApi-&gt;doRequest('https://sandbox...', 'get', Array, Array, 604800)
#3 [internal function]: MyParcelCom\ApiSdk\MyParcelComApi-&gt;MyParcelCom\ApiSdk\{closure}(1, 30)
#4 /var/www/html/integration/vendor/myparcelcom/api-sdk/src/Collection/RequestCollection.php(101): call_user_func_array(Object(Closure), Array)
#5 /var/www/html/integration/vendor/myparcelcom/api-sdk/src/Collection/RequestCollect in`

I was getting the error because I was trying to use the sandbox with live credentials. The actual response is:

`{"errors":[{"status":"403","code":"14000","title":"Invalid OAuth Client","detail":"The supplied client credentials are invalid or the client does not have access to this grant type."}]}`

Cheers, 

James

**Comment by M4tini** [comment] 2022-08-03 11:57
Hi James,

Errors caused by using sandbox credentials on production or vice-versa have been made more clear after you reported this issue. The error has been changed to `Forbidden` with `Client id or client secret is invalid` instead of `Not Found`. Sorry for not updating and closing this issue back then, I will do this now.

Note that there will still be an uncaught exception when using invalid credentials, because the SDK throws exceptions if actions are not allowed. Since communication with an external API is always prone to errors (connectivity or otherwise) it's best to add some form of error handling to your application.

**Closed by M4tini** 2022-08-03 11:58 UTC
